import {ErrorCodes, O23ReservedErrorCode} from '@rainbow-o23/n1';

export const ERR_PIPELINE_TRIGGER_NOT_SUPPORTED: O23ReservedErrorCode = 'O99-00001';
export const ERR_PIPELINE_NOT_FOUND_BY_TRIGGER: O23ReservedErrorCode = 'O99-00002';
export const ERR_SCRIPTS_CONTAINS_INCORRECT_PARAMS: O23ReservedErrorCode = 'O99-00003';
export const ERR_DUPLICATED_PIPELINE: O23ReservedErrorCode = 'O99-00004';
export const ERR_DUPLICATED_PIPELINE_STEP: O23ReservedErrorCode = 'O99-00005';

ErrorCodes.ERR_PIPELINE_TRIGGER_NOT_SUPPORTED = ERR_PIPELINE_TRIGGER_NOT_SUPPORTED;
ErrorCodes.ERR_PIPELINE_NOT_FOUND_BY_TRIGGER = ERR_PIPELINE_NOT_FOUND_BY_TRIGGER;
ErrorCodes.ERR_SCRIPTS_CONTAINS_INCORRECT_PARAMS = ERR_SCRIPTS_CONTAINS_INCORRECT_PARAMS;
ErrorCodes.ERR_DUPLICATED_PIPELINE = ERR_DUPLICATED_PIPELINE;
ErrorCodes.ERR_DUPLICATED_PIPELINE_STEP = ERR_DUPLICATED_PIPELINE_STEP;
