import {ErrorCodes, O23ReservedErrorCode} from '@rainbow-o23/n1';

export const ERR_PIPELINE_HTTP_METHOD_NOT_SUPPORTED: O23ReservedErrorCode = 'O02-00001';
export const ERR_RESPONSE_NOT_FOUND: O23ReservedErrorCode = 'O02-00002';
export const ERR_REQUEST_NOT_FOUND: O23ReservedErrorCode = 'O02-00003';
export const ERR_NO_SCHEDULER_FOUND: O23ReservedErrorCode = 'O02-00004';
export const ERR_DUPLICATE_SCHEDULER: O23ReservedErrorCode = 'O02-00005';

ErrorCodes.ERR_PIPELINE_HTTP_METHOD_NOT_SUPPORTED = ERR_PIPELINE_HTTP_METHOD_NOT_SUPPORTED;
ErrorCodes.ERR_RESPONSE_NOT_FOUND = ERR_RESPONSE_NOT_FOUND;
ErrorCodes.ERR_REQUEST_NOT_FOUND = ERR_REQUEST_NOT_FOUND;
ErrorCodes.ERR_NO_SCHEDULER_FOUND = ERR_NO_SCHEDULER_FOUND;
ErrorCodes.ERR_DUPLICATE_SCHEDULER = ERR_DUPLICATE_SCHEDULER;
