-- author: brad.wu
-- tags: system

CREATE TABLE T_O23_D9_CONFIG
(
    CONFIG_ID        DECIMAL(20) PRIMARY KEY NOT NULL,
    CONFIG_CODE      VARCHAR(32)             NOT NULL,
    CONFIG_NAME      VARCHAR(128)            NOT NULL,
    CONFIG_TYPE      VARCHAR(32)             NOT NULL,
    LANGUAGE         VARCHAR(32)             NULL,
    ENABLED          SMALLINT                NOT NULL DEFAULT 1,
    CONFIG           JSON                    NOT NULL,
    DATA_PIPELINE    JSON                    NULL,
    TENANT_CODE      VARCHAR(64)             NULL,
    VERSION          INT                     NOT NULL DEFAULT 1,
    CREATED_AT       TIMESTAMP               NOT NULL,
    CREATED_BY       VARCHAR(64)             NOT NULL,
    LAST_MODIFIED_AT TIMESTAMP               NOT NULL,
    LAST_MODIFIED_BY VARCHAR(64)             NOT NULL
);
CREATE UNIQUE INDEX I_O23_D9_CONFIG_1 ON T_O23_D9_CONFIG (CONFIG_CODE, LANGUAGE, TENANT_CODE);
CREATE INDEX I_O23_D9_CONFIG_2 ON T_O23_D9_CONFIG (CONFIG_TYPE);
CREATE INDEX I_O23_D9_CONFIG_3 ON T_O23_D9_CONFIG (TENANT_CODE);
COMMENT ON COLUMN T_O23_D9_CONFIG.VERSION IS 'Optimistic lock';
