-- author: brad.wu
-- tags: system

EXEC SP_DROP_CHECK_CONSTRAINT 'T_O23_PRINT_TEMPLATES', 'TEMPLATE_TYPE';
ALTER TABLE T_O23_PRINT_TEMPLATES ADD CONSTRAINT C_O23_PRINT_TEMPLATES_1 CHECK (TEMPLATE_TYPE IN ('PDF', 'EXCEL', 'CSV', 'WORD'));
