import {ErrorCodes, O23ReservedErrorCode} from '@rainbow-o23/n1';

export const ERR_N6_TEMPLATE_NOT_DEFINED: O23ReservedErrorCode = 'O06-00001';
export const ERR_INCORRECT_LOOP_START: O23ReservedErrorCode = 'O06-00002';
export const ERR_NESTED_LOOP_ON_SAME_ARRAY_NOT_ALLOWED: O23ReservedErrorCode = 'O06-00003';
export const ERR_INCORRECT_LOOP_END: O23ReservedErrorCode = 'O06-00004';
export const ERR_INCORRECT_LOOP_END_VARIABLE: O23ReservedErrorCode = 'O06-00005';
export const ERR_UNDETECTABLE_ROW: O23ReservedErrorCode = 'O06-00006';

ErrorCodes.ERR_TEMPLATE_NOT_DEFINED = ERR_N6_TEMPLATE_NOT_DEFINED;
ErrorCodes.ERR_INCORRECT_LOOP_START = ERR_INCORRECT_LOOP_START;
ErrorCodes.ERR_NESTED_LOOP_ON_SAME_ARRAY_NOT_ALLOWED = ERR_NESTED_LOOP_ON_SAME_ARRAY_NOT_ALLOWED;
ErrorCodes.ERR_INCORRECT_LOOP_END = ERR_INCORRECT_LOOP_END;
ErrorCodes.ERR_INCORRECT_LOOP_END_VARIABLE = ERR_INCORRECT_LOOP_END_VARIABLE;
ErrorCodes.ERR_UNDETECTABLE_ROW = ERR_UNDETECTABLE_ROW;
