-- author: brad.wu
-- tags: system

EXEC SP_DROP_CHECK_CONSTRAINT 'T_O23_PRINT_TASKS', 'STATUS';
ALTER TABLE T_O23_PRINT_TASKS ADD CONSTRAINT C_O23_PRINT_TASKS_1 CHECK (STATUS IN ('READY', 'PROCESSING', 'SUCCESS', 'FAIL'));
