import {ErrorCodes, O23ReservedErrorCode} from '@rainbow-o23/n1';

export const ERR_AWS_S3_CREATOR_NOT_FOUND: O23ReservedErrorCode = 'O08-0000';
export const ERR_AWS_REGION_NOT_DEFINED: O23ReservedErrorCode = 'O08-00002';
export const ERR_AWS_CLIENT_NAME_NOT_DEFINED: O23ReservedErrorCode = 'O08-00003';
export const ERR_AWS_S3_BUCKET_NOT_DEFINED: O23ReservedErrorCode = 'O08-00004';
export const ERR_AWS_CREDENTIAL_ACCESS_KEY_NOT_DEFINED: O23ReservedErrorCode = 'O08-00005';
export const ERR_AWS_CREDENTIAL_SECRET_KEY_NOT_DEFINED: O23ReservedErrorCode = 'O08-00006';

ErrorCodes.ERR_AWS_S3_CREATOR_NOT_FOUND = ERR_AWS_S3_CREATOR_NOT_FOUND;
ErrorCodes.ERR_AWS_REGION_NOT_DEFINED = ERR_AWS_REGION_NOT_DEFINED;
ErrorCodes.ERR_AWS_CLIENT_NAME_NOT_DEFINED = ERR_AWS_CLIENT_NAME_NOT_DEFINED;
ErrorCodes.ERR_AWS_S3_BUCKET_NOT_DEFINED = ERR_AWS_S3_BUCKET_NOT_DEFINED;
ErrorCodes.ERR_AWS_CREDENTIAL_ACCESS_KEY_NOT_DEFINED = ERR_AWS_CREDENTIAL_ACCESS_KEY_NOT_DEFINED;
ErrorCodes.ERR_AWS_CREDENTIAL_SECRET_KEY_NOT_DEFINED = ERR_AWS_CREDENTIAL_SECRET_KEY_NOT_DEFINED;
