name: Align version

on:
  workflow_call:
    inputs:
      ref:
        description: The branch or tag name.
        required: true
        type: string
      branch:
        description: Pre-release branch
        required: true
        type: string
      version:
        description: Target version
        required: true
        type: string

jobs:
  align-version:
    name: Align module versions
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: |
          echo "Ref: [${{ inputs.ref }}]"
          echo "Pre-release branch: [${{ inputs.branch }}]"
          echo "Target version: [${{ inputs.version }}]"
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Change Version of o23-n1
        uses: ./.github/actions/change-node-version/
        id: change-node-version-o23-n1
        with:
          module-name: o23-n1
          target-version: ${{ inputs.version }}
      - name: Change Version of o23-n2
        uses: ./.github/actions/change-node-version/
        id: change-node-version-o23-n2
        with:
          module-name: o23-n2
          target-version: ${{ inputs.version }}
      - name: Change Version of o23-n3
        uses: ./.github/actions/change-node-version/
        id: change-node-version-o23-n3
        with:
          module-name: o23-n3
          target-version: ${{ inputs.version }}
      - name: Change Version of o23-n4
        uses: ./.github/actions/change-node-version/
        id: change-node-version-o23-n4
        with:
          module-name: o23-n4
          target-version: ${{ inputs.version }}
      - name: Change Version of o23-n5
        uses: ./.github/actions/change-node-version/
        id: change-node-version-o23-n5
        with:
          module-name: o23-n5
          target-version: ${{ inputs.version }}
      - name: Change Version of o23-n6
        uses: ./.github/actions/change-node-version/
        id: change-node-version-o23-n6
        with:
          module-name: o23-n6
          target-version: ${{ inputs.version }}
      - name: Change Version of o23-n90
        uses: ./.github/actions/change-node-version/
        id: change-node-version-o23-n90
        with:
          module-name: o23-n90
          target-version: ${{ inputs.version }}
      - name: Change Version of o23-n91
        uses: ./.github/actions/change-node-version/
        id: change-node-version-o23-n91
        with:
          module-name: o23-n91
          target-version: ${{ inputs.version }}
      - name: Create pre release branch
        run: git checkout -b ${{ inputs.branch }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "brad.wu"
          git config user.email brad.wu@ebaotech.com
      - name: Commit config and manifest files
        id: make-commit
        run: |
          git add .
          git commit --message "Module version aligned to [${{ inputs.version }}]"
          git tag pre-release-${{ inputs.version }}
      - name: Push new branch
        run: git push --force origin ${{ inputs.branch }} --tags